domain_path: C:\Users\arthu\minimalv2\ws2\platform\export\platform\sw\standalone_ps7_cortexa9_0
app_src_dir: C:\AMDDesignTools\2025.2\Vitis\data\embeddedsw\lib\sw_apps\empty_application
template: empty_application
lang: c
